#!/bin/bash
#based on https://github.com/billkit/cloudflare-DDNS/blob/bc67f68f09abcecb56ef1cbbb087bd993a7244d9/cloudflare-v6.sh but modified. Tested on ubuntu 18.04 & 20.04
auth_email="user@mail.com"
auth_key="xxxxxxxxxxx"
## your cloudflare account key above
zone_name="domain.com"
record_name="record.domain.com"
rec_type=AAAA
interface=eth0

## calls the ipv6_addr.sh script to return an external IPv6 on defined interface above
content=$(/sbin/ifconfig $eth0 | /bin/grep "inet6" | /usr/bin/awk -F " " '{print $2}' | /usr/bin/awk '{print $1}'|/bin/grep -v fe80)

echo $(date) 
echo "Checking $rec_type for $record_name"
zone_id=`curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$zone_name" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json" | \
grep -Eo '"id":"[^"]*' | head -1|sed -n 's/"id":"*//p'` 

echo "Zone ID: " $zone_id

record_id=`curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records?type=$rec_type&name=$record_name" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json" | \
grep -Eo '"id":"[^"]*' | head -1 | sed -n 's/"id":"*//p'`

echo "Record ID: " $record_id

current_content=`curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records/$record_id" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json" | \
grep -Eo '"content":"[^"]*' | head -1 | sed -n 's/"content":"*//p'`

echo "Current Content: " $current_content
echo "New Content: " $content

if [[ $current_content == $content ]]; then
    echo "Content not changed.  Exiting."
    exit 0
else
    echo "Content Changed.  Update Cloudflare."
fi

#time to delete and get it agian
echo "will delete and run agian as of bug"
delete_first=`curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records/$record_id" \
     -H "X-Auth-Email: $auth_email" \
     -H "X-Auth-Key: $auth_key" \
     -H "Content-Type: application/json"`

echo "Zone ID: " $zone_id

record_id=`curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records?type=$rec_type&name=$record_name" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json" | \
grep -Eo '"id":"[^"]*' | head -1 | sed -n 's/"id":"*//p'`

echo "Record ID: " $record_id



update=`curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records/$record_id" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json" \
-d "{\"id\":\"$zone_id\",\"type\":\"$rec_type\",\"name\":\"$record_name\",\"content\":\"$content\"}"`

if [[ $update == *"\"success\":false"* ]]; then
    echo "test"
    #message = "API UPDATE FAILED.  DUMPING RESULTS:\n$update"
    #echo "$message"
    echo "API UPDATE FAILED.  DUMPING RESULTS:\n$update"
    exit 1
else
    message="$record_type changed to: $content"
    echo "$message"
fi
